import type { Locale } from "./dictionaries";
import { paymentReady } from "./checkout";

/**
 * The house's legal and information pages.
 *
 * HARMONISED, V1 feedback §17 (5 Oct 2026). The withdrawal policy, terms §8,
 * the FAQ and the cookie sentences in the imprint, privacy policy and terms
 * now state ONE position (14-day withdrawal; damaged pieces refunded; the
 * cookies this site really sets) — the house asked for exactly this, and the
 * contradictions listed below are kept as the record of what was fixed. The
 * new text is marked `source: null` and needs the house's legal adviser.
 *
 * TRANSCRIBED, NOT WRITTEN (everything else). Every English string below is the client's own
 * text from therootscorner.com, taken verbatim — including its typos, its
 * unfilled bracket, and its contradictions. Raw captures are kept in
 * docs/reference/legal/*.txt so any line here can be checked against the
 * source it came from.
 *
 * Legal copy is the one thing on this site that may not be improved in
 * passing. Where their text is wrong or self-contradicting, the page shows it
 * as written and the problem is raised with the client (CLAUDE.md §9); silently
 * harmonising three inconsistent statements about returns would be inventing a
 * legal position on their behalf.
 *
 * Known problems in the source, ALL reproduced faithfully here:
 *
 *  - Returns contradict three ways. The Withdrawal Policy says returns are
 *    never accepted and all sales are final; the Imprint says customers
 *    "benefit from the right of withdrawal"; and the live site publishes a
 *    "Withdraw contract" form stating contracts may be withdrawn within 14
 *    days. For EU customers the third is the legally operative one.
 *  - Delivery times contradict. This page says Morocco 1–2 weeks and worldwide
 *    2–8; the FAQ says Europe 3–8 weeks; the product records say 1–2 weeks.
 *  - The delivery table charges €80 for orders over €200 and €50 for the same
 *    worldwide shipment, so ordering more costs more to ship.
 *  - Terms §2 still contains an unfilled template bracket.
 *  - The cookie policy describes the OLD Jimdo stack — Jimdo, Stripe, PayPal,
 *    Cloudflare, Google. None of it will be true on this build. It has to be
 *    rewritten against the real stack before launch.
 *  - Typos in the source, left as found: "Adress", "faire trade".
 *
 * FRENCH IS A TRANSLATION (CLAUDE.md §11), not a second draft: no clause is
 * added, dropped or softened. It still needs a lawyer's eye before launch —
 * a faithful translation of a legal text is not the same thing as a legally
 * equivalent one in another jurisdiction.
 */

export type LegalBlock =
  | { kind: "h"; text: string }
  | { kind: "p"; text: string }
  | { kind: "ul"; items: string[] }
  | { kind: "dl"; items: [string, string][] }
  | { kind: "table"; head: string[]; rows: string[][] };

export type LegalDoc = {
  slug: string;
  title: string;
  /**
   * The page on the client's live site this was transcribed from.
   *
   * `null` means the document is OURS, not theirs — currently only the cookie
   * policy, because the client's published one describes the old Jimdo stack
   * (Stripe, PayPal, Cloudflare, Google Analytics) and this build runs none of
   * it. Everything else here is their text, verbatim, and a transcription
   * without a source is a transcription nobody can check.
   */
  source: string | null;
  blocks: LegalBlock[];
};

/** The order they appear in the client's own footer. */
export const LEGAL_SLUGS = [
  "imprint",
  "privacy",
  "cookies",
  "delivery",
  "withdrawal",
  "terms",
] as const;

export type LegalSlug = (typeof LEGAL_SLUGS)[number];

/**
 * The list of destinations, verbatim from the delivery page.
 *
 * Deliberately NOT translated. Two hundred and fifty country names rendered by
 * hand is two hundred and fifty chances to name the wrong country in a shipping
 * policy, and the list is generated by the store platform anyway — Shopify will
 * replace it at launch with its own, in the visitor's language. Leaving it in
 * one language is a blemish; getting one entry wrong is a promise to ship
 * somewhere the client does not.
 */
const COUNTRIES =
  "Aruba, Afghanistan, Angola, Anguilla, Åland Islands, Albania, Andorra, United Arab Emirates, Argentina, Armenia, American Samoa, Antarctica, French Southern Territories, Antigua and Barbuda, Australia, Austria, Azerbaijan, Burundi, Belgium, Benin, Bonaire, Sint Eustatius and Saba, Burkina Faso, Bangladesh, Bulgaria, Bahrain, Bahamas, Bosnia and Herzegovina, Saint Barthélemy, Belize, Bermuda, Bolivia, Plurinational State of, Brazil, Barbados, Brunei Darussalam, Bhutan, Bouvet Island, Botswana, Central African Republic, Canada, Cocos (Keeling) Islands, Switzerland, Chile, China, Côte d’Ivoire, Cameroon, Congo, The Democratic Republic of the, Congo, Cook Islands, Colombia, Comoros, Cabo Verde, Costa Rica, Curaçao, Christmas Island, Cayman Islands, Cyprus, Czechia, Germany, Djibouti, Dominica, Denmark, Dominican Republic, Algeria, Ecuador, Egypt, Eritrea, Western Sahara, Spain, Estonia, Ethiopia, Finland, Fiji, Falkland Islands (Malvinas), France, Faroe Islands, Micronesia, Federated States of, Gabon, United Kingdom, Georgia, Guernsey, Ghana, Gibraltar, Guinea, Guadeloupe, Gambia, Guinea-Bissau, Equatorial Guinea, Greece, Grenada, Greenland, Guatemala, French Guiana, Guam, Guyana, Hong Kong, Heard Island and McDonald Islands, Honduras, Croatia, Haiti, Hungary, Indonesia, Isle of Man, India, British Indian Ocean Territory, Ireland, Iraq, Iceland, Israel, Italy, Jamaica, Jersey, Jordan, Japan, Kazakhstan, Kenya, Kyrgyzstan, Cambodia, Kiribati, Saint Kitts and Nevis, Korea, Republic of, Kuwait, Lao People’s Democratic Republic, Lebanon, Liberia, Libya, Saint Lucia, Liechtenstein, Sri Lanka, Lesotho, Lithuania, Luxembourg, Latvia, Macao, Saint Martin (French part), Morocco, Monaco, Moldova, Republic of, Madagascar, Maldives, Mexico, Marshall Islands, North Macedonia, Mali, Malta, Myanmar, Montenegro, Mongolia, Northern Mariana Islands, Mozambique, Mauritania, Montserrat, Martinique, Mauritius, Malawi, Malaysia, Mayotte, Namibia, New Caledonia, Niger, Norfolk Island, Nigeria, Nicaragua, Niue, Netherlands, Norway, Nepal, Nauru, New Zealand, Oman, Pakistan, Panama, Pitcairn, Peru, Philippines, Palau, Papua New Guinea, Poland, Puerto Rico, Portugal, Paraguay, Palestine, State of, French Polynesia, Qatar, Réunion, Romania, Rwanda, Saudi Arabia, Sudan, Senegal, Singapore, South Georgia and the South Sandwich Islands, Saint Helena, Ascension and Tristan da Cunha, Svalbard and Jan Mayen, Solomon Islands, Sierra Leone, El Salvador, San Marino, Somalia, Saint Pierre and Miquelon, Serbia, South Sudan, Sao Tome and Principe, Suriname, Slovakia, Slovenia, Sweden, Eswatini, Sint Maarten (Dutch part), Seychelles, Turks and Caicos Islands, Chad, Togo, Thailand, Tajikistan, Tokelau, Turkmenistan, Timor-Leste, Tonga, Trinidad and Tobago, Tunisia, Turkey, Tuvalu, Taiwan, Province of China, Tanzania, United Republic of, Uganda, Ukraine, United States Minor Outlying Islands, Uruguay, United States, Uzbekistan, Holy See (Vatican City State), Saint Vincent and the Grenadines, Venezuela, Bolivarian Republic of, Virgin Islands, British, Virgin Islands, U.S., Viet Nam, Vanuatu, Wallis and Futuna, Samoa, Yemen, South Africa, Zambia, Zimbabwe.";

/* ------------------------------------------------------------------ *
 * English — the client's own words
 * ------------------------------------------------------------------ */

const en: Record<string, LegalDoc> = {
  imprint: {
    slug: "imprint",
    title: "Legal Notice",
    source: "https://www.therootscorner.com/imprint/",
    blocks: [
      { kind: "h", text: "1. Legal Information" },
      {
        kind: "p",
        text: "The website The Roots Corner (hereinafter “the Site”) is published by:",
      },
      {
        kind: "dl",
        items: [
          ["Company Name", "The Roots Corner"],
          // "Adress" is the client's spelling. Left as found — corrections to
          // a legal notice come from the client (CLAUDE.md §13).
          ["Adress", "Rue de la liberté 48, 40000 Marrakech, Morocco"],
          ["ICE", "003729558000059"],
          ["RC", "165659"],
        ],
      },
      {
        kind: "p",
        text: "Code of conduct: The roots Corner is committed to conducting its business with integrity, transparency, and respect for ethical values. We prioritize faire trade practices, ensuring that our artisan partners receive fair compensation for their work. We also strive to promote sustainable and responsible sourcing, respecting both cultural heritage and environmental considerations. Discrimination, harassment, corruption, and any unethical behavior are strictly prohibited within our company and in our business relationships. Any violation of this code can be reported to: therootscornerm@gmail.com.",
      },
      {
        kind: "p",
        text: "Characteristics of the economic activity: The Roots Corner specializes in the sale of unique and rare furniture and decorative items sourced from African artisans. Our products are handcrafted and reflect the rich cultural heritage of their origins. We operate as an e-commerce business, selling our products through our online platform and, where applicable, through physical events or pop-up stores. Our mission is to promote authentic craftsmanship while ensuring fair and ethical trade practices.",
      },

      { kind: "h", text: "2. Intellectual Property" },
      {
        kind: "p",
        text: "The content of the Site, including texts, images, videos, logos, graphics, etc., is protected by intellectual property laws and is the exclusive property of The Roots Corner or its partners. Any reproduction, distribution, or modification without prior authorization is prohibited.",
      },

      { kind: "h", text: "3. Personal Data" },
      {
        kind: "p",
        text: "The Roots Corner respects the confidentiality of your personal data and is committed to protecting it in accordance with applicable regulations (including the General Data Protection Regulation - GDPR). Information collected via contact forms or while using the site is used solely for managing your requests.",
      },
      { kind: "p", text: "For more information, please refer to our Privacy Policy." },

      { kind: "h", text: "4. Cookies" },
      {
        kind: "p",
        text: "What this website stores on your device, and why, is set out in our Cookie Policy. You can also manage cookies through your browser settings.",
      },

      { kind: "h", text: "5. External Links" },
      {
        kind: "p",
        text: "The Site may contain links to external websites. The Roots Corner cannot be held responsible for the content of these sites or the use made of them.",
      },

      { kind: "h", text: "6. Limitation of Liability" },
      {
        kind: "p",
        text: "The Site makes every effort to ensure the reliability of the information provided, but cannot be held responsible for errors, omissions, or inaccuracies. The user is solely responsible for the use they make of the information offered on the Site.",
      },

      { kind: "h", text: "7. Regulatory compliance" },
      {
        kind: "p",
        text: "The Roots Corner specializes in selling unique and rare furniture and decorative items from African craftsmanship.",
      },
      {
        kind: "p",
        text: "The activity is not subject to specific authorization but complies with applicable laws regarding:",
      },
      {
        kind: "ul",
        items: [
          "Import regulations: All imported products comply with customs regulations and international trade laws. Any restrictions on materials (e.g., protected woods under CITES) are strictly followed.",
          "Product safety standards: The furniture and decorative items sold meet the necessary safety and quality requirements applicable in the European Union.",
          "Consumer rights: In accordance with e-commerce regulations, customers benefit from the right of withdrawal and clear information regarding delivery, returns, and warranties.",
        ],
      },
      {
        kind: "p",
        text: "For further details, please refer to our Terms and Conditions of Sale.",
      },
    ],
  },

  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    source: "https://www.therootscorner.com/privacy-policy/",
    blocks: [
      { kind: "h", text: "1. Introduction" },
      {
        kind: "p",
        text: "The Roots Corner respects your privacy and is committed to protecting the personal information you provide to us. This privacy policy explains how we collect, use, and protect your personal information when you use our website and services.",
      },

      { kind: "h", text: "2. Collection of personal information" },
      {
        kind: "p",
        text: "We collect the following information when you use our website, subscribe to our newsletter, make a purchase, or otherwise interact with us:",
      },
      {
        kind: "ul",
        items: [
          "Identification information: name, email address, telephone number, postal address.",
          "Payment information: transaction data (via secure third-party payment services).",
          "Browsing Information: browsing data (cookies, IP addresses, browser type, etc.) to improve the user experience.",
          "Other information: any other data that you voluntarily provide to us.",
        ],
      },

      { kind: "h", text: "3. Use of personal information" },
      { kind: "p", text: "The information collected is used to:" },
      {
        kind: "ul",
        items: [
          "Process your orders and deliveries.",
          "Improve and personalise your user experience.",
          "Provide you with information about our products, services and promotions.",
          "Respond to your requests and questions.",
        ],
      },

      { kind: "h", text: "4. Sharing of Personal Information" },
      {
        kind: "p",
        text: "The Roots Corner does not sell or rent your personal information to third parties. However, we may share your information in the following circumstances:",
      },
      {
        kind: "ul",
        items: [
          "Third Party Service Providers: We use third party service providers (payment services, delivery services, etc.) to provide our services to you. These partners have access to the information they need to carry out their work, but may not use it for any other purpose.",
          "Legal obligations: We may need to disclose your information to comply with a legal obligation or to protect our rights.",
        ],
      },

      { kind: "h", text: "5. Protection of personal data" },
      {
        kind: "p",
        text: "We take appropriate security measures to protect your personal information against loss, misuse or unauthorised access. These measures include the use of encryption technologies for financial transactions and security protocols to guarantee data confidentiality.",
      },

      { kind: "h", text: "6. Cookies" },
      {
        kind: "p",
        text: "What this website stores on your device, and why, is set out in our Cookie Policy. You can also manage cookies through your browser settings.",
      },

      { kind: "h", text: "7. Your rights" },
      {
        kind: "p",
        text: "In accordance with personal data protection laws (including the GDPR where applicable), you have the following rights in relation to your data:",
      },
      {
        kind: "ul",
        items: [
          "Right of access: You have the right to request a copy of the personal information we hold about you.",
          "Right of rectification: You can request that we correct any incorrect information.",
          "Right to erasure: You may request the erasure of your personal information.",
          "Right to limit processing: You may request the restriction of the processing of your data.",
          "Right to portability: You may request that your data be sent to you in a structured, commonly used and machine-readable format.",
        ],
      },
      {
        kind: "p",
        text: "To exercise your rights, please contact us at the following address: therootscornerm@gmail.com",
      },

      { kind: "h", text: "8. Changes to the privacy policy" },
      {
        kind: "p",
        text: "We reserve the right to change this privacy policy at any time. Any changes will be posted on this page, together with the date of the last update.",
      },

      { kind: "h", text: "9. Applicable law" },
      {
        kind: "p",
        text: "This privacy policy is governed by Moroccan law. In the event of a dispute, the competent courts will be those of The Roots Corner’s registered office, i.e. in Morocco.",
      },
    ],
  },

  /**
   * REWRITTEN, not transcribed — the one document here that is not the
   * client's own text, and the reason is that theirs is factually wrong about
   * this site.
   *
   * Their published policy describes the Jimdo build: Stripe, PayPal,
   * Cloudflare, Google Maps and Google Analytics, with named cookies and
   * lifetimes for each. This build loads none of them. Reproducing it would
   * have told every visitor that trackers are running which are not, and told
   * every regulator the same — a false statement in a compliance document is
   * worse than a plain one, and CLAUDE.md's rule against inventing facts cuts
   * in this direction too.
   *
   * Everything below was VERIFIED against the code, not assumed:
   *
   *   - no `document.cookie`, no `Set-Cookie`, no cookies() — this site sets
   *     no cookies at all
   *   - no analytics, no tag manager, no third-party script tags
   *   - exactly two browser-storage keys, both first-party and functional:
   *     `trc:cart` (localStorage, the cart) and `trc:intro` (sessionStorage,
   *     so the opening animation plays once per visit)
   *
   * ⚠️ THIS MUST BE RE-CHECKED WHEN THE STACK CHANGES. Turning on Shopify
   * checkout, Google Analytics or Search Console adds third-party cookies and
   * makes this document wrong in the other direction. It is accurate for the
   * build as it stands and for nothing else.
   */
  cookies: {
    slug: "cookies",
    title: "Cookie Policy",
    // Ours, not theirs — see the note on `source` in LegalDoc.
    source: null,
    blocks: [
      {
        kind: "p",
        text: "This website does not use cookies, and it does not use analytics, advertising or third-party tracking of any kind. No consent banner is shown because there is nothing to consent to.",
      },

      { kind: "h", text: "What is stored on your device" },
      {
        kind: "p",
        text: "Two small pieces of information are saved by your own browser so that the site works as you would expect. They are stored on your device only, they are never sent to us or to anyone else, and they contain nothing that identifies you.",
      },
      {
        kind: "dl",
        items: [
          [
            "Your basket",
            "The pieces you have added, so that your basket is still there if you close the tab and come back. Kept until you clear it or your browser clears its site data.",
          ],
          [
            "The opening animation",
            "A note that you have already seen the animation, so that it plays once per visit rather than every time you open a page. Cleared when you close the browser.",
          ],
        ],
      },
      {
        kind: "p",
        text: "You can delete both at any time by clearing this site's data in your browser settings. The site continues to work if you do; you will simply start with an empty basket.",
      },

      { kind: "h", text: "Payment" },
      {
        kind: "p",
        text: "Payment is handled by our payment provider on their own pages. When you go there to pay, that provider's own privacy and cookie terms apply to what happens on those pages. Nothing about a payment is processed on this site.",
      },

      { kind: "h", text: "Links to other services" },
      {
        kind: "p",
        text: "Some links lead to services we do not run, such as Instagram and WhatsApp. Following one takes you to that company, whose own terms then apply. We do not embed their tracking on this site.",
      },
    ],
  },

  delivery: {
    slug: "delivery",
    title: "Delivery Policy",
    source: "https://www.therootscorner.com/delivery-policy/",
    blocks: [
      { kind: "h", text: "Delivery options" },
      {
        kind: "table",
        head: ["Option", "Cost", "Delivery Time"],
        rows: [
          ["Morocco", "€25.00", "1 – 2 Weeks"],
          ["Worldwide", "€50.00", "2 – 8 Weeks"],
          ["Orders €200.00 and up", "€80.00", "2 – 8 Weeks"],
        ],
      },
      { kind: "h", text: "Countries we ship to" },
      { kind: "p", text: COUNTRIES },
    ],
  },

  withdrawal: {
    slug: "withdrawal",
    title: "Withdrawal Policy",
    /*
     * OURS, harmonised — V1 feedback §17 ("high priority"). The house's
     * published text said "no returns will be accepted" and "all sales are
     * final" while its imprint promised a right of withdrawal and its old site
     * published a 14-day withdrawal form. This states one position, the one
     * that is legally operative for EU consumers (and covers Morocco's 7 days),
     * and every other page now points here. The original is kept in
     * docs/reference/legal/. TO BE REVIEWED BY THE HOUSE'S LEGAL ADVISER.
     */
    source: null,
    blocks: [
      { kind: "h", text: "1. Right of withdrawal" },
      {
        kind: "p",
        text: "If you are buying as a consumer, you may withdraw from your purchase within 14 days of receiving it, without giving a reason.",
      },
      {
        kind: "p",
        text: "To do so, tell us clearly within that period — by email at therootscornerm@gmail.com or by WhatsApp — giving your order and the piece concerned.",
      },
      { kind: "h", text: "2. Returning a piece" },
      {
        kind: "p",
        text: "Send the piece back within 14 days of telling us, carefully packed, in the condition in which you received it. Return shipping is at your expense. Our pieces are fragile and most are one of a kind, so we recommend a tracked and insured shipment — write to us first and we will tell you how to pack it safely.",
      },
      { kind: "h", text: "3. Refund" },
      {
        kind: "p",
        text: "We refund the price of the piece and the standard delivery cost within 14 days of your withdrawal, by the payment method you used. We may wait until the piece is back with us. If it comes back damaged by handling beyond what was needed to examine it, the refund may be reduced accordingly.",
      },
      { kind: "h", text: "4. Made-to-measure rugs" },
      {
        kind: "p",
        text: "A Mrirt rug woven to your own dimensions or your own design is made to your specifications, and the right of withdrawal does not apply to it. Finished rugs and rugs from our collections in a listed size are covered by it like any other piece.",
      },
      { kind: "h", text: "5. Pieces damaged on arrival" },
      {
        kind: "p",
        text: "If a piece arrives broken or damaged, contact us as soon as possible after delivery — within 7 days if you can — with photographs of the package and of the piece, and keep the packaging.",
      },
      {
        kind: "p",
        text: "Once the damage is confirmed, we refund the piece in full, delivery included. If you prefer, we can instead arrange a repair where one is possible, or a credit note. A credit note is only ever offered as a choice, never imposed.",
      },
      {
        kind: "p",
        text: "None of this affects the legal guarantees that apply to your purchase.",
      },
    ],
  },

  terms: {
    slug: "terms",
    title: "Terms and Conditions",
    source: "https://www.therootscorner.com/terms-and-conditions/",
    blocks: [
      { kind: "h", text: "1. Intellectual Property Rights" },
      {
        kind: "p",
        text: "The website and all of its components (text, images, logos, graphics, videos, etc.) are the exclusive property of The Roots Corner, unless otherwise stated.",
      },
      {
        kind: "p",
        text: "Any reproduction, display, modification, publication, transmission, or distortion in whole or in part of the website or its content is strictly prohibited without the prior authorization of The Roots Corner.",
      },

      { kind: "h", text: "2. Protection of Personal Data" },
      {
        // The bracket is unfilled on the live site. Left as found — a
        // placeholder is at least visibly a placeholder; guessing what belongs
        // in it would be writing the client's legal text for them.
        kind: "p",
        text: "The information collected on this website is processed for the purpose of managing orders and customer relations, including international ones.",
      },
      {
        kind: "p",
        text: "In accordance with Moroccan laws regarding the protection of personal data as well as the GDPR (if applicable depending on the user’s country), you have:",
      },
      {
        kind: "ul",
        items: [
          "the right to access,",
          "the right to rectification,",
          "the right to erasure,",
          "the right to data portability,",
          "as well as the right to restrict the processing of your data.",
        ],
      },
      {
        kind: "p",
        text: "Data is retained for the period necessary to fulfill the purposes for which it was collected, in compliance with legal retention obligations.",
      },
      {
        kind: "p",
        text: "To exercise these rights, please contact us at the following address: therootscornerm@gmail.com",
      },

      { kind: "h", text: "3. Cookies" },
      {
        kind: "p",
        text: "What this website stores on your device, and why, is set out in our Cookie Policy. You can also manage cookies through your browser settings.",
      },

      { kind: "h", text: "4. Liability" },
      {
        kind: "p",
        text: "The Roots Corner strives to provide accurate and up-to-date information on its website.",
      },
      {
        kind: "p",
        text: "However, the company cannot be held liable for any errors or omissions, nor for any consequences that may result from the use of this information.",
      },
      {
        kind: "p",
        text: "The Roots Corner reserves the right to modify or update the content of the website at any time and without notice.",
      },

      { kind: "h", text: "5. Hyperlinks" },
      {
        kind: "p",
        text: "The website may contain links to third-party websites. The Roots Corner is not responsible for the content of these external websites.",
      },

      { kind: "h", text: "6. Governing Law" },
      { kind: "p", text: "These legal notices are governed by Moroccan law." },
      {
        kind: "p",
        text: "In the event of a dispute, the competent courts shall be those within the jurisdiction of The Roots Corner’s registered office, located in Morocco.",
      },
      {
        kind: "p",
        text: "For international customers, local consumer protection laws may also apply, particularly with regard to returns and refunds.",
      },

      { kind: "h", text: "7. Terms of Sale and Delivery" },
      {
        kind: "p",
        text: "Delivery times vary depending on the destination. Customers are responsible for any applicable customs duties or import taxes.",
      },

      { kind: "h", text: "8. Returns and Refunds" },
      {
        // Harmonised — V1 §17. The withdrawal policy is the one statement.
        kind: "p",
        text: "You have 14 days from receiving your order to withdraw from your purchase. How to return a piece, how refunds are made, and what happens if a piece arrives damaged are set out in our Withdrawal Policy.",
      },
    ],
  },

  faq: {
    slug: "faq",
    title: "FAQ",
    /*
     * OURS, not transcribed (source: null) — the second document after the
     * cookie policy to be rewritten, for the same reason: the client's FAQ had
     * become wrong about this shop. It listed PayPal, Visa, MasterCard and
     * Apple Pay (the store takes bank transfer only, §64), answered "What are
     * the shipping costs?" with delivery times that contradict the product
     * pages (§9.3), and said "all sales are final", which the EU's 14-day
     * withdrawal right overrides (§9.2). The original is kept in
     * docs/reference/legal/faq.txt.
     *
     * Every answer below is a fact the site already holds: the published
     * shipping table, the payment method actually switched on, how accounts
     * and Mrirt orders work. DELIBERATELY ABSENT until the house decides them:
     * delivery times and returns. This text is also the FAQPage markup
     * Google and AI answer engines read, so a wrong answer here is repeated
     * everywhere — update it the day CMI, a returns policy or delivery times
     * are settled.
     */
    source: null,
    blocks: [
      {
        kind: "dl",
        items: [
          [
            "Where do you deliver?",
            "Every piece ships from Marrakech — within Morocco and worldwide, including France, Belgium and Switzerland.",
          ],
          [
            "How much is delivery?",
            "Morocco: €25. International: €50, or €80 for orders of €200 and more. The exact amount is shown at checkout, before you pay.",
          ],
          [
            "How can I pay?",
            "By bank transfer (SEPA). Your bank details arrive with the order confirmation. The piece is reserved for you for 3 days and ships as soon as the transfer arrives.",
          ],
          [
            "Is each piece really unique?",
            "Yes. There is one of each piece, and once it is sold it is not replaced. A sold piece stays on the site, marked as sold.",
          ],
          [
            "How do I follow my order?",
            "Open “My orders” on the site and sign in with your email address — you receive a one-time code, there is no password. You will see your order, its status and, once it has shipped, the tracking link. You are also emailed when it ships.",
          ],
          [
            "Can I order a made-to-measure Mrirt rug?",
            "Yes. Mrirt rugs are handwoven to order by a women’s weaving cooperative in Mrirt, in the Middle Atlas. You choose the size, colour, design and texture: describe the rug you have in mind on the Mrirt rugs page and we contact you personally.",
          ],
          [
            "Are the pieces antique or new?",
            "Both. The collection brings together antique pieces, vintage pieces and recent handmade work. Each piece page says which, and gives its origin and its period where they are known. Where we do not know, we do not say.",
          ],
          [
            "Are the dimensions exact?",
            "They are given as a guide. A handmade object has no perfectly regular measurements, and a few centimetres of difference are possible — a handwoven rug can also vary slightly from its stated size. If a precise measurement matters to you, ask us before buying.",
          ],
          [
            "Are imperfections normal?",
            "Yes. Patina, wear, a small crack, an old repair, an irregular line: these are the marks of time and of the hand, and they are part of the piece. Anything beyond that is shown in the photographs or described on the piece page.",
          ],
          [
            "How long does a made-to-measure rug take?",
            "It depends on the size and the weaving. The time is confirmed with your quote, before you commit to anything.",
          ],
          [
            "Are customs duties included?",
            "No. Outside Morocco, customs duties and import VAT may be charged by the carrier on delivery, depending on your country. They are not included in the price or the delivery cost.",
          ],
          [
            "Can I return a piece?",
            "Yes. You have 14 days from delivery to withdraw from your purchase, and a piece that arrives damaged is refunded in full. The details are in our Withdrawal Policy.",
          ],
          [
            "Can I ask about a piece before buying?",
            "Of course — by WhatsApp, email or the contact form. Every piece page has a link that opens the message already naming the piece.",
          ],
        ],
      },
    ],
  },
};

/* ------------------------------------------------------------------ *
 * French — a translation of the above, not a second draft
 * ------------------------------------------------------------------ */

const fr: Record<string, LegalDoc> = {
  imprint: {
    slug: "imprint",
    title: "Mentions légales",
    source: en.imprint.source,
    blocks: [
      { kind: "h", text: "1. Informations légales" },
      {
        kind: "p",
        text: "Le site The Roots Corner (ci-après « le Site ») est édité par :",
      },
      {
        kind: "dl",
        items: [
          ["Raison sociale", "The Roots Corner"],
          ["Adresse", "Rue de la liberté 48, 40000 Marrakech, Maroc"],
          ["ICE", "003729558000059"],
          ["RC", "165659"],
        ],
      },
      {
        kind: "p",
        text: "Code de conduite : The Roots Corner s’engage à conduire ses activités avec intégrité, transparence et respect des valeurs éthiques. Nous privilégions les pratiques de commerce équitable, en veillant à ce que nos artisans partenaires reçoivent une rémunération juste pour leur travail. Nous nous efforçons également de promouvoir un approvisionnement durable et responsable, respectueux du patrimoine culturel comme des considérations environnementales. La discrimination, le harcèlement, la corruption et tout comportement contraire à l’éthique sont strictement interdits au sein de notre entreprise et dans nos relations commerciales. Toute violation de ce code peut être signalée à : therootscornerm@gmail.com.",
      },
      {
        kind: "p",
        text: "Caractéristiques de l’activité économique : The Roots Corner est spécialisée dans la vente de meubles et d’objets décoratifs uniques et rares provenant d’artisans africains. Nos produits sont fabriqués à la main et reflètent le riche patrimoine culturel de leurs origines. Nous exerçons une activité de commerce en ligne, vendant nos produits via notre plateforme et, le cas échéant, lors d’événements physiques ou de boutiques éphémères. Notre mission est de promouvoir un artisanat authentique tout en garantissant des pratiques commerciales justes et éthiques.",
      },

      { kind: "h", text: "2. Propriété intellectuelle" },
      {
        kind: "p",
        text: "Le contenu du Site, y compris les textes, images, vidéos, logos, graphismes, etc., est protégé par le droit de la propriété intellectuelle et demeure la propriété exclusive de The Roots Corner ou de ses partenaires. Toute reproduction, diffusion ou modification sans autorisation préalable est interdite.",
      },

      { kind: "h", text: "3. Données personnelles" },
      {
        kind: "p",
        text: "The Roots Corner respecte la confidentialité de vos données personnelles et s’engage à les protéger conformément à la réglementation applicable (y compris le Règlement général sur la protection des données — RGPD). Les informations recueillies via les formulaires de contact ou lors de l’utilisation du site servent uniquement à traiter vos demandes.",
      },
      {
        kind: "p",
        text: "Pour plus d’informations, veuillez consulter notre Politique de confidentialité.",
      },

      { kind: "h", text: "4. Cookies" },
      {
        kind: "p",
        text: "Ce que ce site enregistre sur votre appareil, et pourquoi, est détaillé dans notre politique relative aux cookies. Vous pouvez aussi gérer les cookies dans les paramètres de votre navigateur.",
      },

      { kind: "h", text: "5. Liens externes" },
      {
        kind: "p",
        text: "Le Site peut contenir des liens vers des sites externes. The Roots Corner ne saurait être tenue responsable du contenu de ces sites ni de l’usage qui en est fait.",
      },

      { kind: "h", text: "6. Limitation de responsabilité" },
      {
        kind: "p",
        text: "Le Site met tout en œuvre pour assurer la fiabilité des informations fournies, mais ne saurait être tenu responsable des erreurs, omissions ou inexactitudes. L’utilisateur est seul responsable de l’usage qu’il fait des informations proposées sur le Site.",
      },

      { kind: "h", text: "7. Conformité réglementaire" },
      {
        kind: "p",
        text: "The Roots Corner est spécialisée dans la vente de meubles et d’objets décoratifs uniques et rares issus de l’artisanat africain.",
      },
      {
        kind: "p",
        text: "L’activité n’est pas soumise à une autorisation particulière mais respecte les lois applicables en matière de :",
      },
      {
        kind: "ul",
        items: [
          "Réglementation des importations : tous les produits importés respectent la réglementation douanière et le droit du commerce international. Toute restriction portant sur les matériaux (par exemple les bois protégés au titre de la CITES) est strictement respectée.",
          "Normes de sécurité des produits : les meubles et objets décoratifs vendus répondent aux exigences de sécurité et de qualité applicables dans l’Union européenne.",
          "Droits des consommateurs : conformément à la réglementation du commerce électronique, les clients bénéficient du droit de rétractation et d’une information claire concernant la livraison, les retours et les garanties.",
        ],
      },
      {
        kind: "p",
        text: "Pour plus de détails, veuillez consulter nos Conditions générales de vente.",
      },
    ],
  },

  privacy: {
    slug: "privacy",
    title: "Politique de confidentialité",
    source: en.privacy.source,
    blocks: [
      { kind: "h", text: "1. Introduction" },
      {
        kind: "p",
        text: "The Roots Corner respecte votre vie privée et s’engage à protéger les informations personnelles que vous nous communiquez. La présente politique de confidentialité explique comment nous recueillons, utilisons et protégeons vos informations personnelles lorsque vous utilisez notre site et nos services.",
      },

      { kind: "h", text: "2. Collecte des informations personnelles" },
      {
        kind: "p",
        text: "Nous recueillons les informations suivantes lorsque vous utilisez notre site, vous inscrivez à notre lettre d’information, effectuez un achat ou interagissez autrement avec nous :",
      },
      {
        kind: "ul",
        items: [
          "Informations d’identification : nom, adresse e-mail, numéro de téléphone, adresse postale.",
          "Informations de paiement : données de transaction (via des services de paiement tiers sécurisés).",
          "Informations de navigation : données de navigation (cookies, adresses IP, type de navigateur, etc.) afin d’améliorer l’expérience utilisateur.",
          "Autres informations : toute autre donnée que vous nous fournissez volontairement.",
        ],
      },

      { kind: "h", text: "3. Utilisation des informations personnelles" },
      { kind: "p", text: "Les informations recueillies servent à :" },
      {
        kind: "ul",
        items: [
          "Traiter vos commandes et vos livraisons.",
          "Améliorer et personnaliser votre expérience utilisateur.",
          "Vous informer de nos produits, services et promotions.",
          "Répondre à vos demandes et à vos questions.",
        ],
      },

      { kind: "h", text: "4. Partage des informations personnelles" },
      {
        kind: "p",
        text: "The Roots Corner ne vend ni ne loue vos informations personnelles à des tiers. Nous pouvons toutefois les partager dans les cas suivants :",
      },
      {
        kind: "ul",
        items: [
          "Prestataires tiers : nous faisons appel à des prestataires tiers (services de paiement, services de livraison, etc.) pour vous fournir nos services. Ces partenaires ont accès aux informations nécessaires à l’exécution de leur mission, mais ne peuvent les utiliser à d’autres fins.",
          "Obligations légales : nous pouvons être tenus de divulguer vos informations afin de respecter une obligation légale ou de protéger nos droits.",
        ],
      },

      { kind: "h", text: "5. Protection des données personnelles" },
      {
        kind: "p",
        text: "Nous prenons les mesures de sécurité appropriées pour protéger vos informations personnelles contre la perte, l’usage abusif ou l’accès non autorisé. Ces mesures comprennent l’utilisation de technologies de chiffrement pour les transactions financières et de protocoles de sécurité garantissant la confidentialité des données.",
      },

      { kind: "h", text: "6. Cookies" },
      {
        kind: "p",
        text: "Ce que ce site enregistre sur votre appareil, et pourquoi, est détaillé dans notre politique relative aux cookies. Vous pouvez aussi gérer les cookies dans les paramètres de votre navigateur.",
      },

      { kind: "h", text: "7. Vos droits" },
      {
        kind: "p",
        text: "Conformément aux lois sur la protection des données personnelles (dont le RGPD lorsqu’il s’applique), vous disposez des droits suivants sur vos données :",
      },
      {
        kind: "ul",
        items: [
          "Droit d’accès : vous pouvez demander une copie des informations personnelles que nous détenons à votre sujet.",
          "Droit de rectification : vous pouvez demander la correction de toute information inexacte.",
          "Droit à l’effacement : vous pouvez demander la suppression de vos informations personnelles.",
          "Droit à la limitation du traitement : vous pouvez demander la limitation du traitement de vos données.",
          "Droit à la portabilité : vous pouvez demander que vos données vous soient transmises dans un format structuré, couramment utilisé et lisible par machine.",
        ],
      },
      {
        kind: "p",
        text: "Pour exercer vos droits, veuillez nous contacter à l’adresse suivante : therootscornerm@gmail.com",
      },

      { kind: "h", text: "8. Modifications de la politique de confidentialité" },
      {
        kind: "p",
        text: "Nous nous réservons le droit de modifier la présente politique de confidentialité à tout moment. Toute modification sera publiée sur cette page, accompagnée de la date de dernière mise à jour.",
      },

      { kind: "h", text: "9. Droit applicable" },
      {
        kind: "p",
        text: "La présente politique de confidentialité est régie par le droit marocain. En cas de litige, les tribunaux compétents seront ceux du siège social de The Roots Corner, soit au Maroc.",
      },
    ],
  },

  cookies: {
    slug: "cookies",
    title: "Politique relative aux cookies",
    /*
      Ours, not theirs — and a translation of the English above, which was
      verified against the code.

      §46 rewrote the English document because the client's transcribed one
      described Jimdo, Stripe, PayPal, Cloudflare and Google Analytics, none of
      which this build loads. IT MISSED THIS ONE. Until now /fr/legal/cookies
      still opened "Ce site utilise des cookies" and listed a "Marketing /
      tiers" category — false about this build, wrong in the permissive
      direction, and in the locale a French-market regulator actually reads.

      The two locales said opposite things about cookies, live.
    */
    source: null,
    blocks: [
      {
        kind: "p",
        text: "Ce site n’utilise pas de cookies, ni aucune forme de mesure d’audience, de publicité ou de traçage par des tiers. Aucune bannière de consentement n’est affichée, parce qu’il n’y a rien à consentir.",
      },

      { kind: "h", text: "Ce qui est enregistré sur votre appareil" },
      {
        kind: "p",
        text: "Deux informations sont conservées par votre propre navigateur pour que le site se comporte comme vous l’attendez. Elles restent sur votre appareil, ne nous sont jamais transmises — ni à personne d’autre — et ne contiennent rien qui vous identifie.",
      },
      {
        kind: "dl",
        items: [
          [
            "Votre panier",
            "Les pièces que vous avez ajoutées, pour que votre panier soit toujours là si vous fermez l’onglet et revenez. Conservé jusqu’à ce que vous le vidiez ou que votre navigateur efface les données du site.",
          ],
          [
            "L’animation d’ouverture",
            "Une note indiquant que vous l’avez déjà vue, pour qu’elle se joue une fois par visite et non à chaque page. Effacée à la fermeture du navigateur.",
          ],
        ],
      },
      {
        kind: "p",
        text: "Vous pouvez supprimer les deux à tout moment en effaçant les données de ce site dans les réglages de votre navigateur. Le site continue de fonctionner ; vous repartirez simplement d’un panier vide.",
      },

      { kind: "h", text: "Paiement" },
      {
        kind: "p",
        text: "Le paiement est traité par notre prestataire, sur ses propres pages. En vous y rendant pour payer, ce sont ses conditions de confidentialité et de cookies qui s’appliquent. Aucune donnée de paiement n’est traitée sur ce site.",
      },

      { kind: "h", text: "Liens vers d’autres services" },
      {
        kind: "p",
        text: "Certains liens mènent à des services que nous ne gérons pas, comme Instagram et WhatsApp. Les suivre vous conduit chez cette entreprise, dont les conditions s’appliquent alors. Nous n’intégrons aucun de leurs traceurs sur ce site.",
      },
    ],
  },

  delivery: {
    slug: "delivery",
    title: "Livraison",
    source: en.delivery.source,
    blocks: [
      { kind: "h", text: "Options de livraison" },
      {
        kind: "table",
        head: ["Option", "Coût", "Délai"],
        rows: [
          ["Maroc", "25,00 €", "1 – 2 semaines"],
          ["International", "50,00 €", "2 – 8 semaines"],
          ["Commandes à partir de 200,00 €", "80,00 €", "2 – 8 semaines"],
        ],
      },
      { kind: "h", text: "Pays desservis" },
      { kind: "p", text: COUNTRIES },
    ],
  },

  withdrawal: {
    slug: "withdrawal",
    title: "Politique de rétractation",
    // Ours, harmonised — see the English docblock (V1 §17).
    source: null,
    blocks: [
      { kind: "h", text: "1. Droit de rétractation" },
      {
        kind: "p",
        text: "Si vous achetez en tant que consommateur, vous disposez de 14 jours à compter de la réception de votre commande pour vous rétracter, sans avoir à vous justifier.",
      },
      {
        kind: "p",
        text: "Pour cela, informez-nous clairement dans ce délai — par e-mail à therootscornerm@gmail.com ou par WhatsApp — en indiquant votre commande et la pièce concernée.",
      },
      { kind: "h", text: "2. Retour de la pièce" },
      {
        kind: "p",
        text: "Renvoyez la pièce dans les 14 jours qui suivent, soigneusement emballée et dans l’état où vous l’avez reçue. Les frais de retour sont à votre charge. Nos pièces sont fragiles et le plus souvent uniques : nous recommandons un envoi suivi et assuré — écrivez-nous d’abord, nous vous dirons comment l’emballer en toute sécurité.",
      },
      { kind: "h", text: "3. Remboursement" },
      {
        kind: "p",
        text: "Nous remboursons le prix de la pièce et les frais de livraison standard dans les 14 jours suivant votre rétractation, par le moyen de paiement utilisé. Nous pouvons attendre d’avoir récupéré la pièce. Si elle nous revient abîmée par une manipulation allant au-delà de ce qui était nécessaire pour l’examiner, le remboursement peut être réduit d’autant.",
      },
      { kind: "h", text: "4. Tapis sur mesure" },
      {
        kind: "p",
        text: "Un tapis Mrirt tissé selon vos propres dimensions ou votre propre motif est confectionné selon vos spécifications : le droit de rétractation ne s’y applique pas. Les tapis déjà tissés et les tapis de nos collections dans une taille proposée en bénéficient comme toute autre pièce.",
      },
      { kind: "h", text: "5. Pièces endommagées à la réception" },
      {
        kind: "p",
        text: "Si une pièce arrive cassée ou endommagée, contactez-nous dès que possible après la livraison — si possible sous 7 jours — avec des photos du colis et de la pièce, et conservez l’emballage.",
      },
      {
        kind: "p",
        text: "Une fois le dommage constaté, nous remboursons intégralement la pièce, livraison comprise. Si vous le préférez, nous pouvons à la place organiser une réparation lorsqu’elle est possible, ou établir un avoir. L’avoir est toujours proposé comme un choix, jamais imposé.",
      },
      {
        kind: "p",
        text: "Rien de ceci ne limite les garanties légales applicables à votre achat.",
      },
    ],
  },

  terms: {
    slug: "terms",
    title: "Conditions générales",
    source: en.terms.source,
    blocks: [
      { kind: "h", text: "1. Droits de propriété intellectuelle" },
      {
        kind: "p",
        text: "Le site et l’ensemble de ses composants (textes, images, logos, graphismes, vidéos, etc.) sont la propriété exclusive de The Roots Corner, sauf mention contraire.",
      },
      {
        kind: "p",
        text: "Toute reproduction, représentation, modification, publication, transmission ou dénaturation, totale ou partielle, du site ou de son contenu est strictement interdite sans l’autorisation préalable de The Roots Corner.",
      },

      { kind: "h", text: "2. Protection des données personnelles" },
      {
        kind: "p",
        text: "Les informations recueillies sur ce site sont traitées aux fins de la gestion des commandes et de la relation client, y compris à l’international.",
      },
      {
        kind: "p",
        text: "Conformément à la législation marocaine relative à la protection des données personnelles ainsi qu’au RGPD (le cas échéant selon le pays de l’utilisateur), vous disposez :",
      },
      {
        kind: "ul",
        items: [
          "du droit d’accès,",
          "du droit de rectification,",
          "du droit à l’effacement,",
          "du droit à la portabilité des données,",
          "ainsi que du droit à la limitation du traitement de vos données.",
        ],
      },
      {
        kind: "p",
        text: "Les données sont conservées pendant la durée nécessaire aux finalités pour lesquelles elles ont été collectées, dans le respect des obligations légales de conservation.",
      },
      {
        kind: "p",
        text: "Pour exercer ces droits, veuillez nous contacter à l’adresse suivante : therootscornerm@gmail.com",
      },

      { kind: "h", text: "3. Cookies" },
      {
        kind: "p",
        text: "Ce que ce site enregistre sur votre appareil, et pourquoi, est détaillé dans notre politique relative aux cookies. Vous pouvez aussi gérer les cookies dans les paramètres de votre navigateur.",
      },

      { kind: "h", text: "4. Responsabilité" },
      {
        kind: "p",
        text: "The Roots Corner s’efforce de fournir sur son site des informations exactes et à jour.",
      },
      {
        kind: "p",
        text: "La société ne saurait toutefois être tenue responsable des erreurs ou omissions, ni des conséquences pouvant résulter de l’utilisation de ces informations.",
      },
      {
        kind: "p",
        text: "The Roots Corner se réserve le droit de modifier ou de mettre à jour le contenu du site à tout moment et sans préavis.",
      },

      { kind: "h", text: "5. Liens hypertextes" },
      {
        kind: "p",
        text: "Le site peut contenir des liens vers des sites tiers. The Roots Corner n’est pas responsable du contenu de ces sites externes.",
      },

      { kind: "h", text: "6. Droit applicable" },
      { kind: "p", text: "Les présentes mentions légales sont régies par le droit marocain." },
      {
        kind: "p",
        text: "En cas de litige, les tribunaux compétents seront ceux du ressort du siège social de The Roots Corner, situé au Maroc.",
      },
      {
        kind: "p",
        text: "Pour les clients internationaux, les lois locales de protection des consommateurs peuvent également s’appliquer, notamment en matière de retours et de remboursements.",
      },

      { kind: "h", text: "7. Conditions de vente et de livraison" },
      {
        kind: "p",
        text: "Les délais de livraison varient selon la destination. Les droits de douane et taxes à l’importation éventuels sont à la charge du client.",
      },

      { kind: "h", text: "8. Retours et remboursements" },
      {
        kind: "p",
        text: "Vous disposez de 14 jours à compter de la réception de votre commande pour vous rétracter. Les modalités de retour, de remboursement et de prise en charge des pièces endommagées sont précisées dans notre politique de rétractation.",
      },
    ],
  },

  faq: {
    slug: "faq",
    title: "FAQ",
    // Ours — see the English docblock. A translation of it, nothing added.
    source: null,
    blocks: [
      {
        kind: "dl",
        items: [
          [
            "Où livrez-vous ?",
            "Chaque pièce part de Marrakech — au Maroc et dans le monde entier, y compris en France, en Belgique et en Suisse.",
          ],
          [
            "Combien coûte la livraison ?",
            "Maroc : 25 €. International : 50 €, ou 80 € pour les commandes à partir de 200 €. Le montant exact s’affiche au paiement, avant de régler.",
          ],
          [
            "Comment payer ?",
            "Par virement bancaire (SEPA). Nos coordonnées bancaires arrivent avec la confirmation de commande. La pièce vous est réservée 3 jours et part dès réception du virement.",
          ],
          [
            "Chaque pièce est-elle vraiment unique ?",
            "Oui. Il n’existe qu’un exemplaire de chaque pièce, et une pièce vendue n’est pas remplacée. Elle reste visible sur le site, indiquée comme vendue.",
          ],
          [
            "Comment suivre ma commande ?",
            "Ouvrez « Mes commandes » sur le site et connectez-vous avec votre adresse e-mail — vous recevez un code à usage unique, sans mot de passe. Vous y voyez votre commande, son statut et, une fois expédiée, le lien de suivi. Un e-mail vous est aussi envoyé à l’expédition.",
          ],
          [
            "Puis-je commander un tapis Mrirt sur mesure ?",
            "Oui. Les tapis Mrirt sont tissés main sur commande par une coopérative de femmes à Mrirt, dans le Moyen Atlas. Vous choisissez la taille, la couleur, le motif et la texture : décrivez le tapis que vous imaginez sur la page Tapis Mrirt et nous vous contactons personnellement.",
          ],
          [
            "Les pièces sont-elles anciennes ou neuves ?",
            "Les deux. La collection réunit des pièces anciennes, des pièces vintage et des créations artisanales récentes. Chaque fiche indique de quoi il s’agit, avec l’origine et l’époque lorsqu’elles sont connues. Ce que nous ne savons pas, nous ne l’écrivons pas.",
          ],
          [
            "Les dimensions sont-elles exactes ?",
            "Elles sont données à titre indicatif. Un objet fait main n’a pas de mesures parfaitement régulières, et quelques centimètres d’écart sont possibles — un tapis tissé main peut aussi varier légèrement de la taille annoncée. Si une mesure précise compte pour vous, demandez-la-nous avant d’acheter.",
          ],
          [
            "Les imperfections sont-elles normales ?",
            "Oui. Une patine, une usure, une petite fissure, une réparation ancienne, une ligne irrégulière : ce sont les marques du temps et de la main, et elles font partie de la pièce. Tout ce qui va au-delà est montré sur les photos ou décrit sur la fiche.",
          ],
          [
            "Quels sont les délais pour un tapis sur mesure ?",
            "Ils dépendent de la taille et du tissage. Le délai vous est confirmé avec le devis, avant tout engagement.",
          ],
          [
            "Les droits de douane sont-ils inclus ?",
            "Non. Hors du Maroc, des droits de douane et la TVA à l’importation peuvent être demandés par le transporteur à la livraison, selon votre pays. Ils ne sont compris ni dans le prix ni dans les frais de livraison.",
          ],
          [
            "Puis-je retourner une pièce ?",
            "Oui. Vous disposez de 14 jours après la livraison pour vous rétracter, et une pièce arrivée endommagée est remboursée intégralement. Le détail figure dans notre politique de rétractation.",
          ],
          [
            "Puis-je poser une question sur une pièce avant d’acheter ?",
            "Bien sûr — par WhatsApp, e-mail ou le formulaire de contact. Chaque page de pièce propose un lien qui ouvre le message en nommant déjà la pièce.",
          ],
        ],
      },
    ],
  },
};

const docs: Record<Locale, Record<string, LegalDoc>> = { en, fr };

/**
 * The two lines in the Cookie Policy that name who a visitor can be handed to.
 *
 * ---------------------------------------------------------------------------
 * THE COOKIE POLICY TRACKS THE CODE, SO NOBODY HAS TO REMEMBER
 *
 * Four sections of CLAUDE.md say that switching Shopify on is "two jobs" and
 * makes this document wrong in the permissive direction. Checked rather than
 * repeated, that is **overstated**:
 *
 *  · `storefront()` in lib/shopify.ts passes no `credentials`, so fetch
 *    defaults to `same-origin` and a cross-origin `Set-Cookie` is discarded.
 *    The Storefront API cannot put a cookie on this site.
 *  · Checkout is `window.location.href = …` — a whole navigation OFF this
 *    origin. Whatever Shopify stores, it stores on Shopify's domain, under
 *    Shopify's own policy, after the visitor has left.
 *
 * So this site still sets no cookies when payment is live, the statement at the
 * top of the document stays true, and the consent banner correctly stays
 * dormant — there is nothing on this origin to consent to.
 *
 * What genuinely changes is the DISCLOSURE: once payment is live, Shopify is a
 * company a visitor gets handed to, and a document that enumerates those has to
 * name it (§55 — a compliance document is a claim about the code).
 *
 * Which is why these two lines are computed from `paymentReady()` rather than
 * edited by hand. The document cannot drift out of step with the build, in
 * either direction, and there is no step for anyone to forget.
 * ---------------------------------------------------------------------------
 */
function paymentDisclosure(locale: Locale): { payment: string; links: string } {
  const live = paymentReady();

  if (locale === "fr") {
    return {
      payment: live
        ? "Le paiement est traité par Shopify, sur ses propres pages. En vous y rendant pour payer, vous quittez ce site : ce sont les conditions et les cookies de Shopify qui s’appliquent alors. Aucune donnée de paiement n’est traitée ici, et aucun numéro de carte ne transite par ce site."
        : "Le paiement est traité par notre prestataire, sur ses propres pages. En vous y rendant pour payer, ce sont ses conditions de confidentialité et de cookies qui s’appliquent. Aucune donnée de paiement n’est traitée sur ce site.",
      links: live
        ? "Certains liens mènent à des services que nous ne gérons pas — Instagram, WhatsApp et Shopify. Les suivre vous conduit chez cette entreprise, dont les conditions s’appliquent alors. Nous n’intégrons aucun de leurs traceurs sur ce site."
        : "Certains liens mènent à des services que nous ne gérons pas, comme Instagram et WhatsApp. Les suivre vous conduit chez cette entreprise, dont les conditions s’appliquent alors. Nous n’intégrons aucun de leurs traceurs sur ce site.",
    };
  }

  return {
    payment: live
      ? "Payment is handled by Shopify, on their own pages. Going there to pay takes you off this site, and Shopify's own terms and cookies apply from that point. No payment details are processed here, and no card number passes through this site."
      : "Payment is handled by our payment provider on their own pages. When you go there to pay, that provider's own privacy and cookie terms apply to what happens on those pages. Nothing about a payment is processed on this site.",
    links: live
      ? "Some links lead to services we do not run — Instagram, WhatsApp and Shopify. Following one takes you to that company, whose own terms then apply. We do not embed their tracking on this site."
      : "Some links lead to services we do not run, such as Instagram and WhatsApp. Following one takes you to that company, whose own terms then apply. We do not embed their tracking on this site.",
  };
}

export function legalDoc(locale: Locale, slug: string): LegalDoc | undefined {
  const doc = docs[locale][slug];
  if (!doc || slug !== "cookies") return doc;

  /*
    Rewrite the last paragraph of the "Payment" and "Links" sections in place.

    Matched by position — the last `p` after each heading — rather than by
    string, so a wording change upstairs does not silently stop the swap and
    leave the published document a version behind the code.
  */
  const { payment, links } = paymentDisclosure(locale);
  const blocks = doc.blocks.map((b) => ({ ...b }));

  let section: string | null = null;
  for (let i = 0; i < blocks.length; i++) {
    const b = blocks[i] as { kind: string; text?: string };
    if (b.kind === "h") {
      section = b.text ?? null;
      continue;
    }
    if (b.kind !== "p") continue;
    if (section === "Payment" || section === "Paiement") b.text = payment;
    if (section === "Links to other services" || section === "Liens vers d’autres services") {
      b.text = links;
    }
  }

  return { ...doc, blocks };
}

export function isLegalSlug(value: string): value is LegalSlug {
  return (LEGAL_SLUGS as readonly string[]).includes(value);
}
