import type { Locale } from "./dictionaries";

/**
 * The house's legal and information pages.
 *
 * TRANSCRIBED, NOT WRITTEN. Every English string below is the client's own
 * text from therootscorner.com, taken verbatim — including its typos, its
 * unfilled bracket, and its contradictions. Raw captures are kept in
 * docs/reference/legal/*.txt so any line here can be checked against the
 * source it came from.
 *
 * Legal copy is the one thing on this site that may not be improved in
 * passing. Where their text is wrong or self-contradicting, the page shows it
 * as written and the problem is raised with the client (CLAUDE.md §9); silently
 * harmonising three inconsistent statements about returns would be inventing a
 * legal position on their behalf.
 *
 * Known problems in the source, ALL reproduced faithfully here:
 *
 *  - Returns contradict three ways. The Withdrawal Policy says returns are
 *    never accepted and all sales are final; the Imprint says customers
 *    "benefit from the right of withdrawal"; and the live site publishes a
 *    "Withdraw contract" form stating contracts may be withdrawn within 14
 *    days. For EU customers the third is the legally operative one.
 *  - Delivery times contradict. This page says Morocco 1–2 weeks and worldwide
 *    2–8; the FAQ says Europe 3–8 weeks; the product records say 1–2 weeks.
 *  - The delivery table charges €80 for orders over €200 and €50 for the same
 *    worldwide shipment, so ordering more costs more to ship.
 *  - Terms §2 still contains an unfilled template bracket.
 *  - The cookie policy describes the OLD Jimdo stack — Jimdo, Stripe, PayPal,
 *    Cloudflare, Google. None of it will be true on this build. It has to be
 *    rewritten against the real stack before launch.
 *  - Typos in the source, left as found: "Adress", "faire trade".
 *
 * FRENCH IS A TRANSLATION (CLAUDE.md §11), not a second draft: no clause is
 * added, dropped or softened. It still needs a lawyer's eye before launch —
 * a faithful translation of a legal text is not the same thing as a legally
 * equivalent one in another jurisdiction.
 */

export type LegalBlock =
  | { kind: "h"; text: string }
  | { kind: "p"; text: string }
  | { kind: "ul"; items: string[] }
  | { kind: "dl"; items: [string, string][] }
  | { kind: "table"; head: string[]; rows: string[][] };

export type LegalDoc = {
  slug: string;
  title: string;
  /** The page on the client's live site this was transcribed from. */
  source: string;
  blocks: LegalBlock[];
};

/** The order they appear in the client's own footer. */
export const LEGAL_SLUGS = [
  "imprint",
  "privacy",
  "cookies",
  "delivery",
  "withdrawal",
  "terms",
] as const;

export type LegalSlug = (typeof LEGAL_SLUGS)[number];

/**
 * The list of destinations, verbatim from the delivery page.
 *
 * Deliberately NOT translated. Two hundred and fifty country names rendered by
 * hand is two hundred and fifty chances to name the wrong country in a shipping
 * policy, and the list is generated by the store platform anyway — Shopify will
 * replace it at launch with its own, in the visitor's language. Leaving it in
 * one language is a blemish; getting one entry wrong is a promise to ship
 * somewhere the client does not.
 */
const COUNTRIES =
  "Aruba, Afghanistan, Angola, Anguilla, Åland Islands, Albania, Andorra, United Arab Emirates, Argentina, Armenia, American Samoa, Antarctica, French Southern Territories, Antigua and Barbuda, Australia, Austria, Azerbaijan, Burundi, Belgium, Benin, Bonaire, Sint Eustatius and Saba, Burkina Faso, Bangladesh, Bulgaria, Bahrain, Bahamas, Bosnia and Herzegovina, Saint Barthélemy, Belize, Bermuda, Bolivia, Plurinational State of, Brazil, Barbados, Brunei Darussalam, Bhutan, Bouvet Island, Botswana, Central African Republic, Canada, Cocos (Keeling) Islands, Switzerland, Chile, China, Côte d’Ivoire, Cameroon, Congo, The Democratic Republic of the, Congo, Cook Islands, Colombia, Comoros, Cabo Verde, Costa Rica, Curaçao, Christmas Island, Cayman Islands, Cyprus, Czechia, Germany, Djibouti, Dominica, Denmark, Dominican Republic, Algeria, Ecuador, Egypt, Eritrea, Western Sahara, Spain, Estonia, Ethiopia, Finland, Fiji, Falkland Islands (Malvinas), France, Faroe Islands, Micronesia, Federated States of, Gabon, United Kingdom, Georgia, Guernsey, Ghana, Gibraltar, Guinea, Guadeloupe, Gambia, Guinea-Bissau, Equatorial Guinea, Greece, Grenada, Greenland, Guatemala, French Guiana, Guam, Guyana, Hong Kong, Heard Island and McDonald Islands, Honduras, Croatia, Haiti, Hungary, Indonesia, Isle of Man, India, British Indian Ocean Territory, Ireland, Iraq, Iceland, Israel, Italy, Jamaica, Jersey, Jordan, Japan, Kazakhstan, Kenya, Kyrgyzstan, Cambodia, Kiribati, Saint Kitts and Nevis, Korea, Republic of, Kuwait, Lao People’s Democratic Republic, Lebanon, Liberia, Libya, Saint Lucia, Liechtenstein, Sri Lanka, Lesotho, Lithuania, Luxembourg, Latvia, Macao, Saint Martin (French part), Morocco, Monaco, Moldova, Republic of, Madagascar, Maldives, Mexico, Marshall Islands, North Macedonia, Mali, Malta, Myanmar, Montenegro, Mongolia, Northern Mariana Islands, Mozambique, Mauritania, Montserrat, Martinique, Mauritius, Malawi, Malaysia, Mayotte, Namibia, New Caledonia, Niger, Norfolk Island, Nigeria, Nicaragua, Niue, Netherlands, Norway, Nepal, Nauru, New Zealand, Oman, Pakistan, Panama, Pitcairn, Peru, Philippines, Palau, Papua New Guinea, Poland, Puerto Rico, Portugal, Paraguay, Palestine, State of, French Polynesia, Qatar, Réunion, Romania, Rwanda, Saudi Arabia, Sudan, Senegal, Singapore, South Georgia and the South Sandwich Islands, Saint Helena, Ascension and Tristan da Cunha, Svalbard and Jan Mayen, Solomon Islands, Sierra Leone, El Salvador, San Marino, Somalia, Saint Pierre and Miquelon, Serbia, South Sudan, Sao Tome and Principe, Suriname, Slovakia, Slovenia, Sweden, Eswatini, Sint Maarten (Dutch part), Seychelles, Turks and Caicos Islands, Chad, Togo, Thailand, Tajikistan, Tokelau, Turkmenistan, Timor-Leste, Tonga, Trinidad and Tobago, Tunisia, Turkey, Tuvalu, Taiwan, Province of China, Tanzania, United Republic of, Uganda, Ukraine, United States Minor Outlying Islands, Uruguay, United States, Uzbekistan, Holy See (Vatican City State), Saint Vincent and the Grenadines, Venezuela, Bolivarian Republic of, Virgin Islands, British, Virgin Islands, U.S., Viet Nam, Vanuatu, Wallis and Futuna, Samoa, Yemen, South Africa, Zambia, Zimbabwe.";

/* ------------------------------------------------------------------ *
 * English — the client's own words
 * ------------------------------------------------------------------ */

const en: Record<string, LegalDoc> = {
  imprint: {
    slug: "imprint",
    title: "Legal Notice",
    source: "https://www.therootscorner.com/imprint/",
    blocks: [
      { kind: "h", text: "1. Legal Information" },
      {
        kind: "p",
        text: "The website The Roots Corner (hereinafter “the Site”) is published by:",
      },
      {
        kind: "dl",
        items: [
          ["Company Name", "The Roots Corner"],
          // "Adress" is the client's spelling. Left as found — corrections to
          // a legal notice come from the client (CLAUDE.md §13).
          ["Adress", "Rue de la liberté 48, 40000 Marrakech, Morocco"],
          ["ICE", "003729558000059"],
          ["RC", "165659"],
        ],
      },
      {
        kind: "p",
        text: "Code of conduct: The roots Corner is committed to conducting its business with integrity, transparency, and respect for ethical values. We prioritize faire trade practices, ensuring that our artisan partners receive fair compensation for their work. We also strive to promote sustainable and responsible sourcing, respecting both cultural heritage and environmental considerations. Discrimination, harassment, corruption, and any unethical behavior are strictly prohibited within our company and in our business relationships. Any violation of this code can be reported to: therootscornerm@gmail.com.",
      },
      {
        kind: "p",
        text: "Characteristics of the economic activity: The Roots Corner specializes in the sale of unique and rare furniture and decorative items sourced from African artisans. Our products are handcrafted and reflect the rich cultural heritage of their origins. We operate as an e-commerce business, selling our products through our online platform and, where applicable, through physical events or pop-up stores. Our mission is to promote authentic craftsmanship while ensuring fair and ethical trade practices.",
      },

      { kind: "h", text: "2. Intellectual Property" },
      {
        kind: "p",
        text: "The content of the Site, including texts, images, videos, logos, graphics, etc., is protected by intellectual property laws and is the exclusive property of The Roots Corner or its partners. Any reproduction, distribution, or modification without prior authorization is prohibited.",
      },

      { kind: "h", text: "3. Personal Data" },
      {
        kind: "p",
        text: "The Roots Corner respects the confidentiality of your personal data and is committed to protecting it in accordance with applicable regulations (including the General Data Protection Regulation - GDPR). Information collected via contact forms or while using the site is used solely for managing your requests.",
      },
      { kind: "p", text: "For more information, please refer to our Privacy Policy." },

      { kind: "h", text: "4. Cookies" },
      {
        kind: "p",
        text: "The Site uses cookies to enhance user experience, analyze navigation, and for advertising purposes. By continuing to browse the Site, you consent to the use of cookies as outlined in our Cookie Policy.",
      },

      { kind: "h", text: "5. External Links" },
      {
        kind: "p",
        text: "The Site may contain links to external websites. The Roots Corner cannot be held responsible for the content of these sites or the use made of them.",
      },

      { kind: "h", text: "6. Limitation of Liability" },
      {
        kind: "p",
        text: "The Site makes every effort to ensure the reliability of the information provided, but cannot be held responsible for errors, omissions, or inaccuracies. The user is solely responsible for the use they make of the information offered on the Site.",
      },

      { kind: "h", text: "7. Regulatory compliance" },
      {
        kind: "p",
        text: "The Roots Corner specializes in selling unique and rare furniture and decorative items from African craftsmanship.",
      },
      {
        kind: "p",
        text: "The activity is not subject to specific authorization but complies with applicable laws regarding:",
      },
      {
        kind: "ul",
        items: [
          "Import regulations: All imported products comply with customs regulations and international trade laws. Any restrictions on materials (e.g., protected woods under CITES) are strictly followed.",
          "Product safety standards: The furniture and decorative items sold meet the necessary safety and quality requirements applicable in the European Union.",
          "Consumer rights: In accordance with e-commerce regulations, customers benefit from the right of withdrawal and clear information regarding delivery, returns, and warranties.",
        ],
      },
      {
        kind: "p",
        text: "For further details, please refer to our Terms and Conditions of Sale.",
      },
    ],
  },

  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    source: "https://www.therootscorner.com/privacy-policy/",
    blocks: [
      { kind: "h", text: "1. Introduction" },
      {
        kind: "p",
        text: "The Roots Corner respects your privacy and is committed to protecting the personal information you provide to us. This privacy policy explains how we collect, use, and protect your personal information when you use our website and services.",
      },

      { kind: "h", text: "2. Collection of personal information" },
      {
        kind: "p",
        text: "We collect the following information when you use our website, subscribe to our newsletter, make a purchase, or otherwise interact with us:",
      },
      {
        kind: "ul",
        items: [
          "Identification information: name, email address, telephone number, postal address.",
          "Payment information: transaction data (via secure third-party payment services).",
          "Browsing Information: browsing data (cookies, IP addresses, browser type, etc.) to improve the user experience.",
          "Other information: any other data that you voluntarily provide to us.",
        ],
      },

      { kind: "h", text: "3. Use of personal information" },
      { kind: "p", text: "The information collected is used to:" },
      {
        kind: "ul",
        items: [
          "Process your orders and deliveries.",
          "Improve and personalise your user experience.",
          "Provide you with information about our products, services and promotions.",
          "Respond to your requests and questions.",
        ],
      },

      { kind: "h", text: "4. Sharing of Personal Information" },
      {
        kind: "p",
        text: "The Roots Corner does not sell or rent your personal information to third parties. However, we may share your information in the following circumstances:",
      },
      {
        kind: "ul",
        items: [
          "Third Party Service Providers: We use third party service providers (payment services, delivery services, etc.) to provide our services to you. These partners have access to the information they need to carry out their work, but may not use it for any other purpose.",
          "Legal obligations: We may need to disclose your information to comply with a legal obligation or to protect our rights.",
        ],
      },

      { kind: "h", text: "5. Protection of personal data" },
      {
        kind: "p",
        text: "We take appropriate security measures to protect your personal information against loss, misuse or unauthorised access. These measures include the use of encryption technologies for financial transactions and security protocols to guarantee data confidentiality.",
      },

      { kind: "h", text: "6. Cookies" },
      {
        kind: "p",
        text: "We use cookies to improve your experience on our site, analyse traffic and personalise our services. You can configure your browser to refuse cookies or to warn you when a cookie is being sent.",
      },

      { kind: "h", text: "7. Your rights" },
      {
        kind: "p",
        text: "In accordance with personal data protection laws (including the GDPR where applicable), you have the following rights in relation to your data:",
      },
      {
        kind: "ul",
        items: [
          "Right of access: You have the right to request a copy of the personal information we hold about you.",
          "Right of rectification: You can request that we correct any incorrect information.",
          "Right to erasure: You may request the erasure of your personal information.",
          "Right to limit processing: You may request the restriction of the processing of your data.",
          "Right to portability: You may request that your data be sent to you in a structured, commonly used and machine-readable format.",
        ],
      },
      {
        kind: "p",
        text: "To exercise your rights, please contact us at the following address: therootscornerm@gmail.com",
      },

      { kind: "h", text: "8. Changes to the privacy policy" },
      {
        kind: "p",
        text: "We reserve the right to change this privacy policy at any time. Any changes will be posted on this page, together with the date of the last update.",
      },

      { kind: "h", text: "9. Applicable law" },
      {
        kind: "p",
        text: "This privacy policy is governed by Moroccan law. In the event of a dispute, the competent courts will be those of The Roots Corner’s registered office, i.e. in Morocco.",
      },
    ],
  },

  cookies: {
    slug: "cookies",
    title: "Cookie Policy",
    source: "https://www.therootscorner.com/cookie-settings/",
    blocks: [
      {
        kind: "p",
        text: "This website uses cookies. You will find more information about the types of cookies used and you can activate them individually in their respective categories. You can adjust your cookie settings at any time by clicking on the link at the bottom of this site.",
      },

      { kind: "h", text: "Strictly necessary" },
      {
        kind: "p",
        text: "Strictly necessary cookies ensure that the elements of this website function properly. These cookies cannot therefore be deactivated. They are used exclusively by this website and are therefore internal cookies, which means that any information recorded by these cookies will be sent back to this website.",
      },
      {
        kind: "dl",
        items: [
          [
            "Stripe",
            "This is essential in order to enable payments powered by Stripe via this store. Provider: Stripe Inc., 185 Berry Street, Suite 550, San Francisco, CA 94107, USA.",
          ],
          [
            "PayPal",
            "This is essential in order to enable payments powered by Paypal via this store. Provider: PayPal (Europe) S.à r.l. et Cie S.C.A., 22-24 Boulevard Royal, 2449 Luxembourg.",
          ],
          [
            "Cloudflare",
            "Cloudflare is a service providing increased security and performance for websites. Cloudflare offers a content delivery network (“CDN”) to improve the loading times of the website. Provider: Cloudflare Inc., 101 Townsend St, San Francisco, CA 94107, USA. Cookie names and lifetimes: __cfruid (session), __cf_bm (30 minutes), __cf_clearance (30 minutes).",
          ],
          [
            "Web Store State",
            "Essential local storage for the correct functioning of this store and for the continued saving of the visitor’s current shop state. Provider: Jimdo GmbH, Stresemannstrasse 375, 22761 Hamburg, Germany.",
          ],
        ],
      },

      { kind: "h", text: "Functional" },
      {
        kind: "p",
        text: "Functional cookies enable this website to offer you certain functions and to store information already provided (such as a name or language selection) in order to offer you improved and personalised functions.",
      },
      {
        kind: "dl",
        items: [
          [
            "Google Maps",
            "These cookies are set by Google as part of the use of Google Maps. Provider: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA or, if you are resident in the EU, Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland.",
          ],
        ],
      },

      { kind: "h", text: "Marketing / Third Party" },
      {
        kind: "p",
        text: "Marketing/third-party cookies come from external advertising agencies (among others) and are used to collect information about the websites you visit, in order to create targeted advertising for you, for example.",
      },
      { kind: "p", text: "No cookies in this category." },

      { kind: "h", text: "Performance" },
      {
        kind: "p",
        text: "Performance cookies collect information about how a web page is used. We use them to better understand how our pages are used, in order to improve their content and functionality.",
      },
      {
        kind: "dl",
        items: [
          [
            "Google Analytics",
            "These cookies collect anonymous information for analysis purposes, as to how visitors use and interact with this website. Provider: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA or, if you are resident in the EU, Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. Cookie names: _ga, _gat, _gid. Lifetime: 2 years.",
          ],
        ],
      },
    ],
  },

  delivery: {
    slug: "delivery",
    title: "Delivery Policy",
    source: "https://www.therootscorner.com/delivery-policy/",
    blocks: [
      { kind: "h", text: "Delivery options" },
      {
        kind: "table",
        head: ["Option", "Cost", "Delivery Time"],
        rows: [
          ["Morocco", "€25.00", "1 – 2 Weeks"],
          ["Worldwide", "€50.00", "2 – 8 Weeks"],
          ["Orders €200.00 and up", "€80.00", "2 – 8 Weeks"],
        ],
      },
      { kind: "h", text: "Countries we ship to" },
      { kind: "p", text: COUNTRIES },
    ],
  },

  withdrawal: {
    slug: "withdrawal",
    title: "Withdrawal Policy",
    source: "https://www.therootscorner.com/right-of-withdrawal/",
    blocks: [
      { kind: "h", text: "1. Return Policy" },
      {
        kind: "p",
        text: "Due to the fragile nature of our products, returns are not accepted.",
      },
      {
        kind: "p",
        text: "Our items require specific packaging and protection methods to ensure their safety during shipping. Once the package has been opened and handled, we can no longer guarantee that the product can be restored to its original condition or repackaged under conditions identical to those of the original shipment.",
      },
      { kind: "p", text: "Therefore, no returns will be accepted." },

      { kind: "h", text: "2. Refund Policy" },
      {
        kind: "p",
        text: "No refunds will be issued for products that have been ordered and shipped. Given the fragile nature of the items and the risks associated with return shipping, we are unable to restock the products or guarantee their condition after they are returned. Therefore, all sales are considered final once the order has been confirmed.",
      },

      { kind: "h", text: "3. Products Damaged Upon Receipt" },
      {
        kind: "p",
        text: "If your package arrives broken, damaged, or in poor condition upon delivery, please contact us directly as soon as possible after receiving your order.",
      },
      { kind: "p", text: "To process your request, we may ask you for:" },
      {
        kind: "ul",
        items: [
          "photos of the package,",
          "photos of the damaged product,",
          "and proof of purchase.",
        ],
      },
      {
        kind: "p",
        text: "After reviewing your case, we may offer you a gift card as compensation.",
      },

      { kind: "h", text: "4. Claims Policy" },
      {
        kind: "p",
        text: "Any claim regarding a damaged product must be filed within a reasonable time after receiving the package.",
      },
      {
        kind: "p",
        text: "We reserve the right to reject any claim that is incomplete, fraudulent, or does not provide sufficient evidence of the reported damage.",
      },

      { kind: "h", text: "5. Acceptance of Terms" },
      {
        kind: "p",
        text: "By placing an order on our store, you acknowledge that you have read and accepted all of these terms and conditions regarding returns, refunds, and damaged products.",
      },
    ],
  },

  terms: {
    slug: "terms",
    title: "Terms and Conditions",
    source: "https://www.therootscorner.com/terms-and-conditions/",
    blocks: [
      { kind: "h", text: "1. Intellectual Property Rights" },
      {
        kind: "p",
        text: "The website and all of its components (text, images, logos, graphics, videos, etc.) are the exclusive property of The Roots Corner, unless otherwise stated.",
      },
      {
        kind: "p",
        text: "Any reproduction, display, modification, publication, transmission, or distortion in whole or in part of the website or its content is strictly prohibited without the prior authorization of The Roots Corner.",
      },

      { kind: "h", text: "2. Protection of Personal Data" },
      {
        // The bracket is unfilled on the live site. Left as found — a
        // placeholder is at least visibly a placeholder; guessing what belongs
        // in it would be writing the client's legal text for them.
        kind: "p",
        text: "The information collected on this website is processed for the purpose of [purpose of processing, e.g., managing orders and international customer relations].",
      },
      {
        kind: "p",
        text: "In accordance with Moroccan laws regarding the protection of personal data as well as the GDPR (if applicable depending on the user’s country), you have:",
      },
      {
        kind: "ul",
        items: [
          "the right to access,",
          "the right to rectification,",
          "the right to erasure,",
          "the right to data portability,",
          "as well as the right to restrict the processing of your data.",
        ],
      },
      {
        kind: "p",
        text: "Data is retained for the period necessary to fulfill the purposes for which it was collected, in compliance with legal retention obligations.",
      },
      {
        kind: "p",
        text: "To exercise these rights, please contact us at the following address: therootscornerm@gmail.com",
      },

      { kind: "h", text: "3. Cookies" },
      {
        kind: "p",
        text: "This website uses cookies to enhance your user experience and analyze website traffic. You can manage your cookie preferences through your browser settings. For more information, please see our section on cookie settings.",
      },

      { kind: "h", text: "4. Liability" },
      {
        kind: "p",
        text: "The Roots Corner strives to provide accurate and up-to-date information on its website.",
      },
      {
        kind: "p",
        text: "However, the company cannot be held liable for any errors or omissions, nor for any consequences that may result from the use of this information.",
      },
      {
        kind: "p",
        text: "The Roots Corner reserves the right to modify or update the content of the website at any time and without notice.",
      },

      { kind: "h", text: "5. Hyperlinks" },
      {
        kind: "p",
        text: "The website may contain links to third-party websites. The Roots Corner is not responsible for the content of these external websites.",
      },

      { kind: "h", text: "6. Governing Law" },
      { kind: "p", text: "These legal notices are governed by Moroccan law." },
      {
        kind: "p",
        text: "In the event of a dispute, the competent courts shall be those within the jurisdiction of The Roots Corner’s registered office, located in Morocco.",
      },
      {
        kind: "p",
        text: "For international customers, local consumer protection laws may also apply, particularly with regard to returns and refunds.",
      },

      { kind: "h", text: "7. Terms of Sale and Delivery" },
      {
        kind: "p",
        text: "Delivery times vary depending on the destination. Customers are responsible for any applicable customs duties or import taxes.",
      },

      { kind: "h", text: "8. Returns and Refunds" },
      {
        kind: "p",
        text: "Due to the fragile nature of the products offered by The Roots Corner, returns and refunds are not accepted.",
      },
      {
        kind: "p",
        text: "Our items require special packaging to ensure they are protected during shipping. Once shipped and handled after delivery, we can no longer guarantee that they will be returned to their original condition.",
      },
      {
        kind: "p",
        text: "If a package arrives broken or damaged upon delivery, the customer must contact us directly as soon as possible with photos of the package and the affected product.",
      },
      {
        kind: "p",
        text: "After verification, a gift certificate may be offered as compensation.",
      },
    ],
  },

  faq: {
    slug: "faq",
    title: "FAQ",
    source: "https://www.therootscorner.com/faq/",
    blocks: [
      {
        kind: "dl",
        items: [
          [
            "Is delivery available in my city?",
            "Worldwide shipping available. Orders are processed and dispatched as quickly as possible.",
          ],
          [
            "What are the shipping costs?",
            "Delivery within Europe typically takes between 3 and 8 weeks. For destinations in Asia, the Americas, and Australia, delivery times may exceed one month. Should any delays occur, you will be notified by email and kept informed about the status of your order.",
          ],
          [
            "Returns & Refunds",
            "As our products are often fragile and require special packaging, we do not accept returns once an order has been shipped. This allows us to maintain the quality and condition of every piece we offer. All sales are therefore considered final, and refunds cannot be issued for shipped orders.",
          ],
          [
            "What payment methods are available?",
            "Paypal, Visa, MasterCard, Apple pay, Transfert…",
          ],
          [
            "How can you contact us?",
            "If you have any questions, please contact us through our contact page. We will get back to you as soon as possible.",
          ],
        ],
      },
    ],
  },
};

/* ------------------------------------------------------------------ *
 * French — a translation of the above, not a second draft
 * ------------------------------------------------------------------ */

const fr: Record<string, LegalDoc> = {
  imprint: {
    slug: "imprint",
    title: "Mentions légales",
    source: en.imprint.source,
    blocks: [
      { kind: "h", text: "1. Informations légales" },
      {
        kind: "p",
        text: "Le site The Roots Corner (ci-après « le Site ») est édité par :",
      },
      {
        kind: "dl",
        items: [
          ["Raison sociale", "The Roots Corner"],
          ["Adresse", "Rue de la liberté 48, 40000 Marrakech, Maroc"],
          ["ICE", "003729558000059"],
          ["RC", "165659"],
        ],
      },
      {
        kind: "p",
        text: "Code de conduite : The Roots Corner s’engage à conduire ses activités avec intégrité, transparence et respect des valeurs éthiques. Nous privilégions les pratiques de commerce équitable, en veillant à ce que nos artisans partenaires reçoivent une rémunération juste pour leur travail. Nous nous efforçons également de promouvoir un approvisionnement durable et responsable, respectueux du patrimoine culturel comme des considérations environnementales. La discrimination, le harcèlement, la corruption et tout comportement contraire à l’éthique sont strictement interdits au sein de notre entreprise et dans nos relations commerciales. Toute violation de ce code peut être signalée à : therootscornerm@gmail.com.",
      },
      {
        kind: "p",
        text: "Caractéristiques de l’activité économique : The Roots Corner est spécialisée dans la vente de meubles et d’objets décoratifs uniques et rares provenant d’artisans africains. Nos produits sont fabriqués à la main et reflètent le riche patrimoine culturel de leurs origines. Nous exerçons une activité de commerce en ligne, vendant nos produits via notre plateforme et, le cas échéant, lors d’événements physiques ou de boutiques éphémères. Notre mission est de promouvoir un artisanat authentique tout en garantissant des pratiques commerciales justes et éthiques.",
      },

      { kind: "h", text: "2. Propriété intellectuelle" },
      {
        kind: "p",
        text: "Le contenu du Site, y compris les textes, images, vidéos, logos, graphismes, etc., est protégé par le droit de la propriété intellectuelle et demeure la propriété exclusive de The Roots Corner ou de ses partenaires. Toute reproduction, diffusion ou modification sans autorisation préalable est interdite.",
      },

      { kind: "h", text: "3. Données personnelles" },
      {
        kind: "p",
        text: "The Roots Corner respecte la confidentialité de vos données personnelles et s’engage à les protéger conformément à la réglementation applicable (y compris le Règlement général sur la protection des données — RGPD). Les informations recueillies via les formulaires de contact ou lors de l’utilisation du site servent uniquement à traiter vos demandes.",
      },
      {
        kind: "p",
        text: "Pour plus d’informations, veuillez consulter notre Politique de confidentialité.",
      },

      { kind: "h", text: "4. Cookies" },
      {
        kind: "p",
        text: "Le Site utilise des cookies afin d’améliorer l’expérience utilisateur, d’analyser la navigation et à des fins publicitaires. En poursuivant votre navigation sur le Site, vous consentez à l’utilisation des cookies telle que décrite dans notre Politique relative aux cookies.",
      },

      { kind: "h", text: "5. Liens externes" },
      {
        kind: "p",
        text: "Le Site peut contenir des liens vers des sites externes. The Roots Corner ne saurait être tenue responsable du contenu de ces sites ni de l’usage qui en est fait.",
      },

      { kind: "h", text: "6. Limitation de responsabilité" },
      {
        kind: "p",
        text: "Le Site met tout en œuvre pour assurer la fiabilité des informations fournies, mais ne saurait être tenu responsable des erreurs, omissions ou inexactitudes. L’utilisateur est seul responsable de l’usage qu’il fait des informations proposées sur le Site.",
      },

      { kind: "h", text: "7. Conformité réglementaire" },
      {
        kind: "p",
        text: "The Roots Corner est spécialisée dans la vente de meubles et d’objets décoratifs uniques et rares issus de l’artisanat africain.",
      },
      {
        kind: "p",
        text: "L’activité n’est pas soumise à une autorisation particulière mais respecte les lois applicables en matière de :",
      },
      {
        kind: "ul",
        items: [
          "Réglementation des importations : tous les produits importés respectent la réglementation douanière et le droit du commerce international. Toute restriction portant sur les matériaux (par exemple les bois protégés au titre de la CITES) est strictement respectée.",
          "Normes de sécurité des produits : les meubles et objets décoratifs vendus répondent aux exigences de sécurité et de qualité applicables dans l’Union européenne.",
          "Droits des consommateurs : conformément à la réglementation du commerce électronique, les clients bénéficient du droit de rétractation et d’une information claire concernant la livraison, les retours et les garanties.",
        ],
      },
      {
        kind: "p",
        text: "Pour plus de détails, veuillez consulter nos Conditions générales de vente.",
      },
    ],
  },

  privacy: {
    slug: "privacy",
    title: "Politique de confidentialité",
    source: en.privacy.source,
    blocks: [
      { kind: "h", text: "1. Introduction" },
      {
        kind: "p",
        text: "The Roots Corner respecte votre vie privée et s’engage à protéger les informations personnelles que vous nous communiquez. La présente politique de confidentialité explique comment nous recueillons, utilisons et protégeons vos informations personnelles lorsque vous utilisez notre site et nos services.",
      },

      { kind: "h", text: "2. Collecte des informations personnelles" },
      {
        kind: "p",
        text: "Nous recueillons les informations suivantes lorsque vous utilisez notre site, vous inscrivez à notre lettre d’information, effectuez un achat ou interagissez autrement avec nous :",
      },
      {
        kind: "ul",
        items: [
          "Informations d’identification : nom, adresse e-mail, numéro de téléphone, adresse postale.",
          "Informations de paiement : données de transaction (via des services de paiement tiers sécurisés).",
          "Informations de navigation : données de navigation (cookies, adresses IP, type de navigateur, etc.) afin d’améliorer l’expérience utilisateur.",
          "Autres informations : toute autre donnée que vous nous fournissez volontairement.",
        ],
      },

      { kind: "h", text: "3. Utilisation des informations personnelles" },
      { kind: "p", text: "Les informations recueillies servent à :" },
      {
        kind: "ul",
        items: [
          "Traiter vos commandes et vos livraisons.",
          "Améliorer et personnaliser votre expérience utilisateur.",
          "Vous informer de nos produits, services et promotions.",
          "Répondre à vos demandes et à vos questions.",
        ],
      },

      { kind: "h", text: "4. Partage des informations personnelles" },
      {
        kind: "p",
        text: "The Roots Corner ne vend ni ne loue vos informations personnelles à des tiers. Nous pouvons toutefois les partager dans les cas suivants :",
      },
      {
        kind: "ul",
        items: [
          "Prestataires tiers : nous faisons appel à des prestataires tiers (services de paiement, services de livraison, etc.) pour vous fournir nos services. Ces partenaires ont accès aux informations nécessaires à l’exécution de leur mission, mais ne peuvent les utiliser à d’autres fins.",
          "Obligations légales : nous pouvons être tenus de divulguer vos informations afin de respecter une obligation légale ou de protéger nos droits.",
        ],
      },

      { kind: "h", text: "5. Protection des données personnelles" },
      {
        kind: "p",
        text: "Nous prenons les mesures de sécurité appropriées pour protéger vos informations personnelles contre la perte, l’usage abusif ou l’accès non autorisé. Ces mesures comprennent l’utilisation de technologies de chiffrement pour les transactions financières et de protocoles de sécurité garantissant la confidentialité des données.",
      },

      { kind: "h", text: "6. Cookies" },
      {
        kind: "p",
        text: "Nous utilisons des cookies pour améliorer votre expérience sur notre site, analyser le trafic et personnaliser nos services. Vous pouvez configurer votre navigateur pour refuser les cookies ou vous avertir lorsqu’un cookie est envoyé.",
      },

      { kind: "h", text: "7. Vos droits" },
      {
        kind: "p",
        text: "Conformément aux lois sur la protection des données personnelles (dont le RGPD lorsqu’il s’applique), vous disposez des droits suivants sur vos données :",
      },
      {
        kind: "ul",
        items: [
          "Droit d’accès : vous pouvez demander une copie des informations personnelles que nous détenons à votre sujet.",
          "Droit de rectification : vous pouvez demander la correction de toute information inexacte.",
          "Droit à l’effacement : vous pouvez demander la suppression de vos informations personnelles.",
          "Droit à la limitation du traitement : vous pouvez demander la limitation du traitement de vos données.",
          "Droit à la portabilité : vous pouvez demander que vos données vous soient transmises dans un format structuré, couramment utilisé et lisible par machine.",
        ],
      },
      {
        kind: "p",
        text: "Pour exercer vos droits, veuillez nous contacter à l’adresse suivante : therootscornerm@gmail.com",
      },

      { kind: "h", text: "8. Modifications de la politique de confidentialité" },
      {
        kind: "p",
        text: "Nous nous réservons le droit de modifier la présente politique de confidentialité à tout moment. Toute modification sera publiée sur cette page, accompagnée de la date de dernière mise à jour.",
      },

      { kind: "h", text: "9. Droit applicable" },
      {
        kind: "p",
        text: "La présente politique de confidentialité est régie par le droit marocain. En cas de litige, les tribunaux compétents seront ceux du siège social de The Roots Corner, soit au Maroc.",
      },
    ],
  },

  cookies: {
    slug: "cookies",
    title: "Politique relative aux cookies",
    source: en.cookies.source,
    blocks: [
      {
        kind: "p",
        text: "Ce site utilise des cookies. Vous trouverez ci-dessous des informations sur les types de cookies utilisés et vous pouvez les activer individuellement dans leurs catégories respectives. Vous pouvez ajuster vos préférences à tout moment en cliquant sur le lien en bas de ce site.",
      },

      { kind: "h", text: "Strictement nécessaires" },
      {
        kind: "p",
        text: "Les cookies strictement nécessaires assurent le bon fonctionnement des éléments de ce site. Ils ne peuvent donc pas être désactivés. Ils sont utilisés exclusivement par ce site et sont donc des cookies internes, ce qui signifie que toute information enregistrée par ces cookies est renvoyée à ce site.",
      },
      {
        kind: "dl",
        items: [
          [
            "Stripe",
            "Indispensable pour permettre les paiements assurés par Stripe sur cette boutique. Fournisseur : Stripe Inc., 185 Berry Street, Suite 550, San Francisco, CA 94107, États-Unis.",
          ],
          [
            "PayPal",
            "Indispensable pour permettre les paiements assurés par PayPal sur cette boutique. Fournisseur : PayPal (Europe) S.à r.l. et Cie S.C.A., 22-24 Boulevard Royal, 2449 Luxembourg.",
          ],
          [
            "Cloudflare",
            "Cloudflare est un service qui renforce la sécurité et les performances des sites web. Cloudflare fournit un réseau de diffusion de contenu (« CDN ») afin d’améliorer les temps de chargement. Fournisseur : Cloudflare Inc., 101 Townsend St, San Francisco, CA 94107, États-Unis. Noms et durées de vie : __cfruid (session), __cf_bm (30 minutes), __cf_clearance (30 minutes).",
          ],
          [
            "Web Store State",
            "Stockage local indispensable au bon fonctionnement de la boutique et à la conservation de l’état de la visite en cours. Fournisseur : Jimdo GmbH, Stresemannstrasse 375, 22761 Hambourg, Allemagne.",
          ],
        ],
      },

      { kind: "h", text: "Fonctionnels" },
      {
        kind: "p",
        text: "Les cookies fonctionnels permettent à ce site de vous proposer certaines fonctions et de mémoriser des informations déjà fournies (comme un nom ou un choix de langue) afin de vous offrir des fonctionnalités améliorées et personnalisées.",
      },
      {
        kind: "dl",
        items: [
          [
            "Google Maps",
            "Ces cookies sont déposés par Google dans le cadre de l’utilisation de Google Maps. Fournisseur : Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, États-Unis ou, si vous résidez dans l’UE, Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irlande.",
          ],
        ],
      },

      { kind: "h", text: "Marketing / tiers" },
      {
        kind: "p",
        text: "Les cookies marketing et tiers proviennent notamment de régies publicitaires externes et servent à recueillir des informations sur les sites que vous visitez, par exemple afin de vous proposer des publicités ciblées.",
      },
      { kind: "p", text: "Aucun cookie dans cette catégorie." },

      { kind: "h", text: "Performance" },
      {
        kind: "p",
        text: "Les cookies de performance recueillent des informations sur la façon dont une page est utilisée. Nous les utilisons pour mieux comprendre l’usage de nos pages, afin d’en améliorer le contenu et les fonctionnalités.",
      },
      {
        kind: "dl",
        items: [
          [
            "Google Analytics",
            "Ces cookies recueillent des informations anonymes à des fins d’analyse, sur la façon dont les visiteurs utilisent ce site et interagissent avec lui. Fournisseur : Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, États-Unis ou, si vous résidez dans l’UE, Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irlande. Noms : _ga, _gat, _gid. Durée de vie : 2 ans.",
          ],
        ],
      },
    ],
  },

  delivery: {
    slug: "delivery",
    title: "Livraison",
    source: en.delivery.source,
    blocks: [
      { kind: "h", text: "Options de livraison" },
      {
        kind: "table",
        head: ["Option", "Coût", "Délai"],
        rows: [
          ["Maroc", "25,00 €", "1 – 2 semaines"],
          ["International", "50,00 €", "2 – 8 semaines"],
          ["Commandes à partir de 200,00 €", "80,00 €", "2 – 8 semaines"],
        ],
      },
      { kind: "h", text: "Pays desservis" },
      { kind: "p", text: COUNTRIES },
    ],
  },

  withdrawal: {
    slug: "withdrawal",
    title: "Droit de rétractation",
    source: en.withdrawal.source,
    blocks: [
      { kind: "h", text: "1. Politique de retour" },
      {
        kind: "p",
        text: "En raison de la fragilité de nos produits, les retours ne sont pas acceptés.",
      },
      {
        kind: "p",
        text: "Nos pièces nécessitent un emballage et des méthodes de protection spécifiques pour garantir leur sécurité durant le transport. Une fois le colis ouvert et manipulé, nous ne pouvons plus garantir que le produit puisse être remis dans son état d’origine ni remballé dans des conditions identiques à celles de l’envoi initial.",
      },
      { kind: "p", text: "Par conséquent, aucun retour ne sera accepté." },

      { kind: "h", text: "2. Politique de remboursement" },
      {
        kind: "p",
        text: "Aucun remboursement ne sera effectué pour les produits commandés et expédiés. Compte tenu de la fragilité des pièces et des risques liés au transport de retour, nous ne pouvons ni les remettre en stock ni garantir leur état après retour. Toute vente est donc considérée comme définitive dès la confirmation de la commande.",
      },

      { kind: "h", text: "3. Produits endommagés à la réception" },
      {
        kind: "p",
        text: "Si votre colis arrive cassé, endommagé ou en mauvais état, veuillez nous contacter directement dès que possible après réception de votre commande.",
      },
      { kind: "p", text: "Pour traiter votre demande, nous pouvons vous demander :" },
      {
        kind: "ul",
        items: [
          "des photos du colis,",
          "des photos du produit endommagé,",
          "et une preuve d’achat.",
        ],
      },
      {
        kind: "p",
        text: "Après examen de votre dossier, nous pourrons vous proposer une carte cadeau à titre de compensation.",
      },

      { kind: "h", text: "4. Politique de réclamation" },
      {
        kind: "p",
        text: "Toute réclamation concernant un produit endommagé doit être formulée dans un délai raisonnable après réception du colis.",
      },
      {
        kind: "p",
        text: "Nous nous réservons le droit de rejeter toute réclamation incomplète, frauduleuse ou n’apportant pas de preuve suffisante du dommage signalé.",
      },

      { kind: "h", text: "5. Acceptation des conditions" },
      {
        kind: "p",
        text: "En passant commande sur notre boutique, vous reconnaissez avoir lu et accepté l’ensemble de ces conditions relatives aux retours, aux remboursements et aux produits endommagés.",
      },
    ],
  },

  terms: {
    slug: "terms",
    title: "Conditions générales",
    source: en.terms.source,
    blocks: [
      { kind: "h", text: "1. Droits de propriété intellectuelle" },
      {
        kind: "p",
        text: "Le site et l’ensemble de ses composants (textes, images, logos, graphismes, vidéos, etc.) sont la propriété exclusive de The Roots Corner, sauf mention contraire.",
      },
      {
        kind: "p",
        text: "Toute reproduction, représentation, modification, publication, transmission ou dénaturation, totale ou partielle, du site ou de son contenu est strictement interdite sans l’autorisation préalable de The Roots Corner.",
      },

      { kind: "h", text: "2. Protection des données personnelles" },
      {
        kind: "p",
        text: "Les informations recueillies sur ce site sont traitées aux fins de [finalité du traitement, par exemple : gestion des commandes et des relations clients à l’international].",
      },
      {
        kind: "p",
        text: "Conformément à la législation marocaine relative à la protection des données personnelles ainsi qu’au RGPD (le cas échéant selon le pays de l’utilisateur), vous disposez :",
      },
      {
        kind: "ul",
        items: [
          "du droit d’accès,",
          "du droit de rectification,",
          "du droit à l’effacement,",
          "du droit à la portabilité des données,",
          "ainsi que du droit à la limitation du traitement de vos données.",
        ],
      },
      {
        kind: "p",
        text: "Les données sont conservées pendant la durée nécessaire aux finalités pour lesquelles elles ont été collectées, dans le respect des obligations légales de conservation.",
      },
      {
        kind: "p",
        text: "Pour exercer ces droits, veuillez nous contacter à l’adresse suivante : therootscornerm@gmail.com",
      },

      { kind: "h", text: "3. Cookies" },
      {
        kind: "p",
        text: "Ce site utilise des cookies afin d’améliorer votre expérience utilisateur et d’analyser le trafic. Vous pouvez gérer vos préférences via les paramètres de votre navigateur. Pour plus d’informations, consultez notre section relative aux cookies.",
      },

      { kind: "h", text: "4. Responsabilité" },
      {
        kind: "p",
        text: "The Roots Corner s’efforce de fournir sur son site des informations exactes et à jour.",
      },
      {
        kind: "p",
        text: "La société ne saurait toutefois être tenue responsable des erreurs ou omissions, ni des conséquences pouvant résulter de l’utilisation de ces informations.",
      },
      {
        kind: "p",
        text: "The Roots Corner se réserve le droit de modifier ou de mettre à jour le contenu du site à tout moment et sans préavis.",
      },

      { kind: "h", text: "5. Liens hypertextes" },
      {
        kind: "p",
        text: "Le site peut contenir des liens vers des sites tiers. The Roots Corner n’est pas responsable du contenu de ces sites externes.",
      },

      { kind: "h", text: "6. Droit applicable" },
      { kind: "p", text: "Les présentes mentions légales sont régies par le droit marocain." },
      {
        kind: "p",
        text: "En cas de litige, les tribunaux compétents seront ceux du ressort du siège social de The Roots Corner, situé au Maroc.",
      },
      {
        kind: "p",
        text: "Pour les clients internationaux, les lois locales de protection des consommateurs peuvent également s’appliquer, notamment en matière de retours et de remboursements.",
      },

      { kind: "h", text: "7. Conditions de vente et de livraison" },
      {
        kind: "p",
        text: "Les délais de livraison varient selon la destination. Les droits de douane et taxes à l’importation éventuels sont à la charge du client.",
      },

      { kind: "h", text: "8. Retours et remboursements" },
      {
        kind: "p",
        text: "En raison de la fragilité des produits proposés par The Roots Corner, les retours et remboursements ne sont pas acceptés.",
      },
      {
        kind: "p",
        text: "Nos pièces nécessitent un emballage spécifique afin d’être protégées durant le transport. Une fois expédiées puis manipulées après livraison, nous ne pouvons plus garantir qu’elles seront restituées dans leur état d’origine.",
      },
      {
        kind: "p",
        text: "Si un colis arrive cassé ou endommagé à la livraison, le client doit nous contacter directement dès que possible, avec des photos du colis et du produit concerné.",
      },
      {
        kind: "p",
        text: "Après vérification, un bon d’achat pourra être proposé à titre de compensation.",
      },
    ],
  },

  faq: {
    slug: "faq",
    title: "FAQ",
    source: en.faq.source,
    blocks: [
      {
        kind: "dl",
        items: [
          [
            "La livraison est-elle possible dans ma ville ?",
            "Livraison dans le monde entier. Les commandes sont traitées et expédiées dans les meilleurs délais.",
          ],
          [
            "Quels sont les frais de livraison ?",
            "La livraison en Europe prend généralement entre 3 et 8 semaines. Pour l’Asie, les Amériques et l’Australie, les délais peuvent dépasser un mois. En cas de retard, vous serez informé par e-mail et tenu au courant de l’état de votre commande.",
          ],
          [
            "Retours et remboursements",
            "Nos produits étant souvent fragiles et nécessitant un emballage particulier, nous n’acceptons pas les retours une fois la commande expédiée. Cela nous permet de préserver la qualité et l’état de chaque pièce que nous proposons. Toute vente est donc considérée comme définitive, et aucun remboursement ne peut être effectué pour les commandes expédiées.",
          ],
          [
            "Quels moyens de paiement sont acceptés ?",
            "PayPal, Visa, MasterCard, Apple Pay, virement…",
          ],
          [
            "Comment nous contacter ?",
            "Pour toute question, contactez-nous via notre page contact. Nous vous répondrons dès que possible.",
          ],
        ],
      },
    ],
  },
};

const docs: Record<Locale, Record<string, LegalDoc>> = { en, fr };

export function legalDoc(locale: Locale, slug: string): LegalDoc | undefined {
  return docs[locale][slug];
}

export function isLegalSlug(value: string): value is LegalSlug {
  return (LEGAL_SLUGS as readonly string[]).includes(value);
}
